syntax = "Lua51"
column_width = 88
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
space_after_function_names = "Never"
collapse_simple_statement = "ConditionalOnly"

[sort_requires]
enabled = true
